fix: var t shadowing global i18n t() function
In submitFormula() and renderHistoryPanel(), 'var t' loop variable
was hoisted to function top, overriding the global t() i18n function
and causing 'Uncaught TypeError: t is not a function'.